# Default values for opcua.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 444505633365.dkr.ecr.eu-west-3.amazonaws.com/opcua-connector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "prd-v1.0.8"

config:
  appName: "opcua-connector"
  appEnvironment: "production"
  loggerLocal: "false"
  opcuaServerHostname: ""
  opcuaServerPort: ""
  opcuaUserName: ""
  opcuaPassword: ""
  cronName: ""
  cronExpression: ""
  citronDataSourceValue: ""
  citronExternalApiKey: ""
  citronExternalApiEndpoint: ""
  citronCallbackKey: ""
  citronCallbackEndpoint: ""
  secretProviderClassName: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

# We can use the user 1000 and a readonly root filesystem for OPCUA
securityContext:
  runAsUser: 1000
  readOnlyRootFilesystem: true
  # capabilities:
  #   drop:
  #   - ALL
  # runAsNonRoot: true

service:
  {}
  # type: NodePort
  # port: 8080

resources:
  limits:
    cpu: 2
    memory: 4096Mi
  requests:
    cpu: 2
    memory: 4096Mi

# readinessProbe configuration is intentionally set to use `ls` command.
# This is because OPC UA does not run continuously, and using `ls` is a lightweight method to check for the container's basic operational status.
readinessProbe:
  exec:
    command: ["ls"]
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5

# livenessProbe configuration also uses the `ls` command for similar reasons.
# It's a simple, non-intrusive way to ensure the container is still operational, given that OPC UA does not run continuously.
livenessProbe:
  exec:
    command: ["ls"]
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
