{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opcua.fullname" . }}
  labels:
    {{- include "opcua.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: opcua
  selector:
    {{- include "opcua.selectorLabels" . | nindent 4 }}
{{- end }}